"""Resolution of the external toolchain prefixes used by the physics backends.

The single source of truth is ``.hadros3-env.mk``, written by ``make setup``:
the Makefile includes it and the Python layer reads it here, so a checkout never
depends on one developer's home directory.

Resolution order for every prefix:

1. an explicit environment variable (``HADROS3_PYTHIA8_PREFIX``,
   ``HADROS3_GEANT4_PREFIX``, ``HADROS3_CONDA_PREFIX``);
2. ``.hadros3-env.mk`` as generated by ``make setup``;
3. the active conda environment (``CONDA_PREFIX``);
4. the conventional micromamba locations, including the legacy ``dis``
   environment of the original development machine.

The last candidate is returned even when nothing exists, so error messages keep
naming a concrete path instead of ``None``.
"""

from __future__ import annotations

import os
from functools import lru_cache
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENV_FILE = ROOT / ".hadros3-env.mk"

LEGACY_PREFIXES = [
    Path.home() / "micromamba" / "envs" / "dis",
    Path.home() / "micromamba" / "envs" / "hadros3",
]

PYTHIA8_MARKER = Path("include") / "Pythia8" / "Pythia.h"
GEANT4_MARKERS = [Path("lib") / "cmake" / "Geant4", Path("lib64") / "cmake" / "Geant4"]


@lru_cache(maxsize=1)
def env_file_values() -> dict[str, str]:
    """Parse the ``KEY := value`` lines of the generated .hadros3-env.mk."""
    values: dict[str, str] = {}
    if not ENV_FILE.exists():
        return values
    for line in ENV_FILE.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or ":=" not in line:
            continue
        key, _, value = line.partition(":=")
        value = value.strip()
        if value and "$(" not in value:
            values[key.strip()] = value
    return values


def _candidates(env_var: str, file_key: str) -> list[Path]:
    found: list[Path] = []
    values = env_file_values()
    for raw in (os.environ.get(env_var), values.get(file_key), values.get("HADROS3_CONDA_PREFIX")):
        if raw:
            found.append(Path(raw))
    active = os.environ.get("CONDA_PREFIX")
    if active:
        found.append(Path(active))
    found.extend(LEGACY_PREFIXES)
    unique: list[Path] = []
    for path in found:
        if path not in unique:
            unique.append(path)
    return unique


def _first_with(candidates: list[Path], markers: list[Path]) -> Path:
    for candidate in candidates:
        for marker in markers:
            if (candidate / marker).exists():
                return candidate
    return candidates[-1]


def pythia8_prefix() -> Path:
    """Installation prefix providing PYTHIA 8 and HepMC3."""
    return _first_with(_candidates("HADROS3_PYTHIA8_PREFIX", "PYTHIA8_PREFIX"), [PYTHIA8_MARKER])


def geant4_prefix() -> Path:
    """Installation prefix providing the Geant4 CMake package and datasets."""
    return _first_with(_candidates("HADROS3_GEANT4_PREFIX", "GEANT4_PREFIX"), GEANT4_MARKERS)


def conda_prefix() -> Path:
    """Best guess for the environment holding the shared physics libraries."""
    return _first_with(_candidates("HADROS3_CONDA_PREFIX", "HADROS3_CONDA_PREFIX"), [Path("lib")])
